### ISSUE TITLE
It will be great to have a dockerized version of this workload.

### ISSUE THREAD

**Issue by aruneshchandra** [Node-DC/Node-DC-EIS#2]

**Comment by sushmakt** [comment]
Hi Arunesh,
We have a patch for the dockerized version(https://github.com/Node-DC/Node-DC-EIS/pull/3/commits/65a36bc31a5338bd3aa91383006844f9b4da00bc)
Can you please review it and let us know of any feedback.
-Sushma

**Comment by uttampawar** [comment]
@aruneshchandra 
Did you get a chance to try the patch as mentioned by @sushmakt? Any feedback?

**Comment by lostintangent** [comment]
@uttampawar Would it make sense for there to be a separate `Dockerfile` for each of the services defined in `Node-DC-EIS-microservices`? That way their respective containers could be deployed/scaled/updated individually within a cluster.

**Comment by uttampawar** [comment]
@lostintangent Yes, it does. Is this something you are interested in or have immediate use? It could be a good contribution if you are ready to submit a PR?

**Comment by lostintangent** [comment]
@uttampawar I'd definitely be interested in this, and we'd use it as part of the benchmarks we want to run for Kubernetes on Azure (I'd also love to see Kubernetes yaml scripts added to this project 😄).

I won't be able to get to this within the next week or so, but I'd be happy to help contribute.

**Comment by uttampawar** [comment]
@sushmakt @lostintangent,
Is there any update to this issue?

**Comment by aruneshchandra** [comment]
@lostintangent and I have worked on this and now we are able to run this workload on Kubernetes clusters on ACS and GCP. I am planning to submit a PR to enable this workflow.

**Comment by uttampawar** [comment]
@aruneshchandra @lostintangent We are approaching a date to release v1.0 of this workload. I would like to see your PR to include in the next release. Thanks.

**Comment by aruneshchandra** [comment]
@uttampawar - when is the new release ?

**Comment by uttampawar** [comment]
@aruneshchandra Sorry for the delay. We have planned the release by end of Jun.

**Comment by uttampawar** [comment]
@aruneshchandra @lostintangent We released v1.0 of this workload. Now it supports simple SSR mode using PUG (aka Jade) in addition of default JSON response and multiple instance run for higher CPU/system utilization on a machine with large number of cores or across pool of machines.

**Comment by uttampawar** [comment]
@aruneshchandra I'll close this issue, since this workload has been dockerized. Feel free to reopen if you find any issue.
