### ISSUE TITLE
Refactor Node-DC-EIS into multiple repositories

### ISSUE THREAD

**Issue by uttampawar** [Node-DC/Node-DC-EIS#20]
This is issue to track refactoring effort of Node-DC-EIS.git into multiple repositories as follows, and add them back into Node-DC-EIS as git submodule if needed.

Node-DC/
-- Node-DC-EIS-client or Node-DC-client
-- Node-DC-EIS
-- Node-DC-EIS-pug
-- Node-DC-EIS-reactjs
-- Node-DC-EIS-microservices

This would make it easier to add more use cases and independent development.
Any feedback, opinion would be greatly appreciated.

**Comment by egalli** [comment]
@uttampawar Are we still doing this? PR #31 was made 24 days ago but it hasn't had any activity
