### ISSUE TITLE
Client changes to test PUG - server side rendering use case

### ISSUE THREAD

**Issue by uttampawar** [Node-DC/Node-DC-EIS#26]
@egalli Do you have client changes to test PUG implementation? Please issue a PR and refer this issue if you they can be merged with current runspec.py.

**Comment by egalli** [comment]
As I noted in the pug PR, the changes can't be merged right now. Waiting for changes for #25 to merged first. Too many conflicts because of how we currently "import" _node_dc_eis_testurls.py_ and how we send GET requests (socket vs request module).

**Comment by uttampawar** [comment]
@egalli Can you merge client changes now that we have merged latest update from runspec?
