### ISSUE TITLE
There is a bug in Line 686 of Node-DC-EIS-cluster/controllers/employees_controller.js

### ISSUE THREAD

**Issue by cwz920716** [Node-DC/Node-DC-EIS#4]
Hi,
  I believe there is a typo error in Line 686 of Node-DC-EIS-cluster/controllers/employees_controller.js. callback() function shouldn't be called since it is undefined in the last parameter of async.parallel since it is undefined. I got following error when running it:

ReferenceError: callback is not defined
    at /home/trinity/NodeJS/Node-DC-EIS/Node-DC-EIS-cluster/controllers/employees_controller.js:686:16
    at /home/trinity/NodeJS/Node-DC-EIS/Node-DC-EIS-cluster/node_modules/async/dist/async.js:3694:9
    at /home/trinity/NodeJS/Node-DC-EIS/Node-DC-EIS-cluster/node_modules/async/dist/async.js:356:16
    at iteratorCallback (/home/trinity/NodeJS/Node-DC-EIS/Node-DC-EIS-cluster/node_modules/async/dist/async.js:934:13)
    at /home/trinity/NodeJS/Node-DC-EIS/Node-DC-EIS-cluster/node_modules/async/dist/async.js:840:16
    at /home/trinity/NodeJS/Node-DC-EIS/Node-DC-EIS-cluster/node_modules/async/dist/async.js:3691:13
    at apply (/home/trinity/NodeJS/Node-DC-EIS/Node-DC-EIS-cluster/node_modules/async/dist/async.js:21:25)
    at /home/trinity/NodeJS/Node-DC-EIS/Node-DC-EIS-cluster/node_modules/async/dist/async.js:56:12
    at findOneAddress (/home/trinity/NodeJS/Node-DC-EIS/Node-DC-EIS-cluster/controllers/employees_controller.js:631:20)
    at /home/trinity/NodeJS/Node-DC-EIS/Node-DC-EIS-cluster/node_modules/mongoose/lib/model.js:3419:16
    at /home/trinity/NodeJS/Node-DC-EIS/Node-DC-EIS-cluster/node_modules/kareem/index.js:212:48
    at /home/trinity/NodeJS/Node-DC-EIS/Node-DC-EIS-cluster/node_modules/kareem/index.js:127:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Thanks,
Wenzhi Cui

**Comment by priyankasprakash** [comment]
Hi, We have fixed this issue and merged the changes.
