### ISSUE TITLE
Server starting issue

### ISSUE THREAD

**Issue by uttampawar** [Node-DC/Node-DC-EIS#55]
Currently, server starts even if mongoldb connection fails due to various reason such as, wrong db_url or if mongodb server is not running. The solution would be to exit if it fails to connect to the database server causing unnecessary and erroneous execution of the workload.

**Comment by priyankasprakash** [comment]
This commit fixes the issue- https://github.com/Node-DC/Node-DC-EIS/pull/54/commits/a30bc62be41258991d297592ca4889791eaa0e44
