### ISSUE TITLE
Mongoose Deprecation Warning

### ISSUE THREAD

**Issue by yweijiang** [Node-DC/Node-DC-EIS#6]
When calling runspec.py from a client, the server that is running server-cluster.js throws out a lot of these warnings:

(node:5352) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

I am using Mongoose version 4.7.7, and MongoDB version 3.4.1. I was not able to get server-cluster.js to run at all with Mongoose version 3.9.*, and the warnings happen for all versions of Node.js that I tried.

**Comment by litian2025** [comment]
Adding some context with regard to this issue: We are trying to set up Node-DV-EIS workload and basically follow the instructions, we hit numerous deprecation warnings above, is this expected? Could you please post your tested configuration on Windows so we can duplicate the settings and make further progress? Thanks.

**Comment by uttampawar** [comment]
These warning are currently expected due to feature deprecation in mongoose driver. You can still use the workload to continue your work.

**Comment by uttampawar** [comment]
@yweijiang @litian2025 I'll close this issue since there is a workaround. We will re-open or open a new one if needed.
