### ISSUE TITLE
Error message in version checking after running with Chakracore version of Node

### ISSUE THREAD

**Issue by yweijiang** [Node-DC/Node-DC-EIS#8]
runspec.py prints an error message saying the detected version of Node is V8 with an empty version number when running using the Chakracore.

**Comment by uttampawar** [comment]
@yweijiang Has this been resolved? Is there a PR?

**Comment by yweijiang** [comment]
@uttampawar Yes, this has been resolved along with the other issue. Both fixes are in the email I sent to you and Priyanka with fixes for runspec.py on 3/9. It appears these fixes were never actually made to the repo. @priyankasprakash could you check this?

**Comment by priyankasprakash** [comment]
Yes, I have a patch for this that @yweijiang sent. I will submit it.

**Comment by uttampawar** [comment]
@priyankasprakash Please submit the patch as you stated in your last comment. Thanks,

**Comment by uttampawar** [comment]
@priyankasprakash Has this issue been addressed with latest commit?

**Comment by priyankasprakash** [comment]
This issue will be fixed with these changes - https://github.com/Node-DC/Node-DC-EIS/pull/40

**Comment by uttampawar** [comment]
@yweijiang This has been fixed upstream.
